---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.1
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: make fmt LOCAL=1
        language: system
        stages: [ commit-msg ]
      - id: security-analysis
        name: security-analysis
        entry: make security-analysis LOCAL=1
        language: system
        stages: [ commit-msg ]
      - id: static-analysis
        name: static-analysis
        entry: make static-analysis LOCAL=1
        language: system
        stages: [ commit-msg ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: no-commit-to-branch
        stages: [ commit-msg ]
        args: [ --branch, master ]
