networks:
  project:
    name: project

services:
  # applications

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      ENVIRONMENT: "production"
      VERSION: "${VERSION:-latest}"
      TZ: "${TZ}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      OAUTH_SECRET: "${OAUTH_SECRET}"
      OAUTH_EXPIRATION_DAYS: "${OAUTH_EXPIRATION_DAYS}"
      HTTP_HOST: "${HTTP_HOST}"
      HTTP_PORT: "${HTTP_PORT}"
      MONGODB_ROOT_USERNAME: "${MONGODB_ROOT_USERNAME}"
      MONGODB_ROOT_PASSWORD: "${MONGODB_ROOT_PASSWORD}"
      MONGODB_ROOT_DATABASE: "${MONGODB_ROOT_DATABASE}"
      MONGODB_USERNAME: "${MONGODB_USERNAME}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
      MONGODB_DATABASE: "${MONGODB_DATABASE}"
      MONGODB_HOST: "${MONGODB_HOST}"
      MONGODB_PORT: "${MONGODB_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
      EMAIL_FROM: "${EMAIL_FROM}"
      EMAIL_UI_PORT: "${EMAIL_UI_PORT}"
    image: ${REGISTRY}/app:${VERSION}
    networks:
      - project

version: "3.7"
