version: "3.8"

volumes:
  example_mongodb:
    external: true
  example_rabbitmq:
    external: true

services:
  service_configurator_http:
    build:
      target: development
    ports:
      - 81:80
    volumes:
      - .:/app
    restart: always
    command: "src/apps/configurator_http/__main__.py"

  mongodb:
    container_name: mongodb
    image: mongo:4.2.8
    volumes:
      - example_mongodb:/data/db
      - example_mongodb:/var/log/mongodb
    restart: always
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGODB_ROOT_DATABASE}"
    networks:
      - example

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    volumes:
      - example_rabbitmq:/var/lib/rabbitmq
      - example_rabbitmq:/var/log/rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}"
    environment:
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_ROOT_VHOST}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_ROOT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_ROOT_PASSWORD}"
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
    networks:
      - example