version: "3.8"

x-env-vars:
  &env-vars
  _: "_"

x-consumer-config:
  &consumer-config
  build:
    context: .
    dockerfile: docker/python/Dockerfile
    target: app_cli_production
  restart: unless-stopped
  environment:
    <<: *env-vars
  networks:
    - example

services:
  skeleton_cli_consumer_on_internal_user_deleted:
    container_name: skeleton_cli_consumer_on_internal_user_deleted
    <<: *consumer-config
    command: src/apps/app_cli skeleton:account:consumer-on-internal-user-deleted
