version: "3.8"

x-env-vars:
  &env-vars
  ENVIRONMENT: "${ENVIRONMENT:-development}"

x-services-config:
  &services-config
  volumes:
    - .:/app
  restart: unless-stopped
  environment:
    <<: *env-vars
  networks:
    - example

services:
  cnf:
    container_name: cnf
    <<: *services-config
    build:
      target: cnf_http_development
    ports:
      - "${CNF_PORT}:${CNF_PORT}"

  app:
    container_name: app
    <<: *services-config
    build:
      target: app_http_development
    ports:
      - "${APP_PORT}:${APP_PORT}"
