name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  CI:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'
      - name: Run actions/setup-docker@macos-latest
        uses: docker-practice/actions-setup-docker@1.0.2
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Run actions/setup-docker-compose@v2
        run: pip3 install docker-compose

      - name: build
        timeout-minutes: 5
        run: |
          docker login docker.pkg.github.com --username "${{github.actor}}" --password "${{github.token}}"
          make build
      - name: deps
        timeout-minutes: 1
        run: make deps

      - name: start
        timeout-minutes: 1
        run: make start

      - name: validate-docker
        timeout-minutes: 1
        run: make validate-docker

      - name: security-analysis
        timeout-minutes: 1
        run: make security-analysis

      - name: static-analysis
        timeout-minutes: 1
        run: make static-analysis

      - name: test
        timeout-minutes: 3
        run: make test

      - name: stop
        timeout-minutes: 1
        run: make stop

      - name: clean
        timeout-minutes: 1
        run: |
          make clean
          docker logout docker.pkg.github.com