name: Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  REGISTRY: "localhost"
  VERSION: ${{ github.sha }}
  LOCAL: 0

jobs:
  ContinuosIntegration:
    timeout-minutes: 16
    runs-on: ${{ matrix.os }}
    env:
      DEPLOY: 0
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - name: Run actions/setup-docker-compose@v2
        run: mkdir -p $HOME/bin && curl -L "https://github.com/docker/compose/releases/download/`curl -fsSLI -o /dev/null -w %{url_effective} https://github.com/docker/compose/releases/latest | sed 's#.*tag/##g' && echo`/docker-compose-$(uname -s)-$(uname -m)" -o $HOME/bin/docker-compose && chmod +x $HOME/bin/docker-compose

      - name: validate-docker
        timeout-minutes: 1
        run: make validate-docker

      - name: build
        timeout-minutes: 5
        run: make build

      - name: start
        timeout-minutes: 2
        run: make start

      - name: security-analysis
        timeout-minutes: 1
        run: make security-analysis

      - name: static-analysis
        timeout-minutes: 1
        run: make static-analysis

      - name: test
        timeout-minutes: 3
        run: make test

      - name: stop
        timeout-minutes: 1
        run: make stop

      - name: clean
        timeout-minutes: 1
        run: make clean
